public class Constants {
    public static final String UNDER_APPROVAL_PROCESS_ERR_MSG = System.Label.Under_Approval_Error_Msg;
    public static final string OPP_Mngr_APPROVAL_PROCESS = 'X1st_Level_Discount_Approval';
    public static final string Mngr_APPROVAL_PROCESS_MSG = 'Submitting for Manager Approval';    
    public static final string OPP_MD_APPROVAL_PROCESS = 'X2nd_Level_Discount_Approval';
    public static final string MD_APPROVAL_PROCESS_MSG = 'Submitting for MD Approval';    
}